version = 1

test_patterns = [
    "awx/**/tests/**/test_*.py",
    "awx_collection/test/awx/test_*.py",
    "awxkit/test/test_*.py"
]

exclude_patterns = [
    "docs/**",
    "tools/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements/requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
